### ISSUE TITLE
貌似fragment会有一些奇怪的问题

### ISSUE THREAD

**Issue by sunjun2009311** [forvv231/EasyNavigation#25]
在使用中，出现很多奇怪的问题，比如fragment中的组件会有“失灵”的情况：重新进入主Activity时候调用显示某些组件然而无法显示的情况，我不知道是什么原因导致的，所以也不确定是导航栏的问题，但是我重新销毁重建主Activity后就不会有那么多的问题了。

**Comment by forvv231** [comment]
过段时间activity销毁，fragment中gatactivity会报null，如果是这个问题跟咱们这个是没关系的------------------ 原始邮件 ------------------
发件人: "jan"<notifications@github.com>
发送时间: 2019年7月26日(星期五) 上午10:01
收件人: "forvv231/EasyNavigation"<EasyNavigation@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [forvv231/EasyNavigation] 貌似fragment会有一些奇怪的问题 (#25)



在使用中，出现很多奇怪的问题，比如fragment中的组&#x4EF6;会有“失灵”的情况：重新进入主Activity时候调用显示某些组&#x4EF6;然而无法显示的情况，我不知道是什么原因导致的，所以也不确定是导航栏的问题，但是我重新销毁重建主Activity后就不会有那么多的问题了。
 
&mdash;

**Comment by sunjun2009311** [comment]
emmm,我已经换成TabHost的方式了，问题就没有了。我的3个fragment都有listview组件 ，可能跟内存占用有点关系。
